{{- define "common.pvc" -}}
---
{{- range .Values.persistentVolumeClaims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- toYaml (.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  resources:
    {{- toYaml .resources | nindent 4 }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
---
{{- end }}
{{- end }}