{{- $volumes := list }}
{{- $volumeMounts := list }}
{{- $envVars := dict }}

{{- range .Values.volumes }}
  {{- $volume := omit . "mount" }}
  {{- $volumes = append $volumes $volume }}
  {{- if hasKey . "mount" }}
    {{- $volumeMount := merge (dict "name" .name) .mount }}
    {{- $volumeMounts = append $volumeMounts $volumeMount }}
  {{- end }}
{{- end }}

{{- range .Values.persistentVolumeClaims }}
  {{- $volume := dict
      "name" .name
      "persistentVolumeClaim"
        (dict "claimName" (printf "%s-%s" (include "common.fullname" $) .name))
  }}
  {{- $volumes = append $volumes $volume }}

  {{- if hasKey . "mount" }}
    {{- $volumeMount := merge (dict "name" .name) .mount }}
    {{- $volumeMounts = append $volumeMounts $volumeMount }}
  {{- end }}
{{- end }}

{{- range .Values.envVarsBase }}
  {{- $_ := set $envVars .name . }}
{{- end }}
{{- range .Values.envVars }}
  {{- $_ := set $envVars .name . }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers: {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.name" . }}
          {{- if .Values.securityContext}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
           {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
           {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if gt (len $volumeMounts) 0 }}
          volumeMounts:
            {{- range $volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if $envVars}}
          env:
          {{- range $name, $entry := $envVars }}
            - name: {{ $entry.name | quote }}
              {{- if hasKey $entry "valueFrom" }}
              valueFrom: {{ toYaml $entry.valueFrom | nindent 16 }}
              {{- else }}
              value: {{ $entry.value | quote }}
              {{- end }}
          {{- end }}
          {{- end }}
      {{- if gt (len $volumes) 0 }}
      volumes:
        {{- toYaml $volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
