{{- $servicePorts := list }}
{{- range .Values.ports }}
  {{- if hasKey . "servicePort" }}
    {{- $servicePorts = append $servicePorts . }}
  {{- end }}
{{- end }}

{{- if $servicePorts }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $servicePorts }}
    - name: {{ .name }}
      port: {{ .servicePort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}