{{- if or (not .Values.ports) (eq (len .Values.ports) 0) -}}
  {{- fail "You must define .Values.ports with at least one port entry." -}}
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ required (printf "No servicePort or containerPort defined for port '%s'" .name) (or .servicePort .containerPort) }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
